info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - 配置检查
  /user/login:
    post:
      consumes:
      - application/json
      description: do ping
      parameters:
      - description: username
        in: formData
        name: username
        type: string
      - description: password
        in: formData
        name: password
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "data":""}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 用户
  /user/register:
    post:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - 用户管理
swagger: "2.0"
